// All world countries sorted by phone prefix
export const WORLD_COUNTRIES: { code: string; name: string; phonePrefix: string }[] = [
  { code: "US", name: "United States", phonePrefix: "1" },
  { code: "CA", name: "Canada", phonePrefix: "1" },
  { code: "RU", name: "Russia", phonePrefix: "7" },
  { code: "KZ", name: "Kazakhstan", phonePrefix: "7" },
  { code: "EG", name: "Egypt", phonePrefix: "20" },
  { code: "ZA", name: "South Africa", phonePrefix: "27" },
  { code: "GR", name: "Greece", phonePrefix: "30" },
  { code: "NL", name: "Netherlands", phonePrefix: "31" },
  { code: "BE", name: "Belgium", phonePrefix: "32" },
  { code: "FR", name: "France", phonePrefix: "33" },
  { code: "ES", name: "Spain", phonePrefix: "34" },
  { code: "HU", name: "Hungary", phonePrefix: "36" },
  { code: "IT", name: "Italy", phonePrefix: "39" },
  { code: "RO", name: "Romania", phonePrefix: "40" },
  { code: "CH", name: "Switzerland", phonePrefix: "41" },
  { code: "AT", name: "Austria", phonePrefix: "43" },
  { code: "GB", name: "United Kingdom", phonePrefix: "44" },
  { code: "DK", name: "Denmark", phonePrefix: "45" },
  { code: "SE", name: "Sweden", phonePrefix: "46" },
  { code: "NO", name: "Norway", phonePrefix: "47" },
  { code: "PL", name: "Poland", phonePrefix: "48" },
  { code: "DE", name: "Germany", phonePrefix: "49" },
  { code: "PE", name: "Peru", phonePrefix: "51" },
  { code: "MX", name: "Mexico", phonePrefix: "52" },
  { code: "CU", name: "Cuba", phonePrefix: "53" },
  { code: "AR", name: "Argentina", phonePrefix: "54" },
  { code: "BR", name: "Brazil", phonePrefix: "55" },
  { code: "CL", name: "Chile", phonePrefix: "56" },
  { code: "CO", name: "Colombia", phonePrefix: "57" },
  { code: "VE", name: "Venezuela", phonePrefix: "58" },
  { code: "MY", name: "Malaysia", phonePrefix: "60" },
  { code: "AU", name: "Australia", phonePrefix: "61" },
  { code: "ID", name: "Indonesia", phonePrefix: "62" },
  { code: "PH", name: "Philippines", phonePrefix: "63" },
  { code: "NZ", name: "New Zealand", phonePrefix: "64" },
  { code: "SG", name: "Singapore", phonePrefix: "65" },
  { code: "TH", name: "Thailand", phonePrefix: "66" },
  { code: "JP", name: "Japan", phonePrefix: "81" },
  { code: "KR", name: "South Korea", phonePrefix: "82" },
  { code: "VN", name: "Vietnam", phonePrefix: "84" },
  { code: "CN", name: "China", phonePrefix: "86" },
  { code: "TR", name: "Turkey", phonePrefix: "90" },
  { code: "IN", name: "India", phonePrefix: "91" },
  { code: "PK", name: "Pakistan", phonePrefix: "92" },
  { code: "AF", name: "Afghanistan", phonePrefix: "93" },
  { code: "LK", name: "Sri Lanka", phonePrefix: "94" },
  { code: "MM", name: "Myanmar", phonePrefix: "95" },
  { code: "IR", name: "Iran", phonePrefix: "98" },
  { code: "SS", name: "South Sudan", phonePrefix: "211" },
  { code: "MA", name: "Morocco", phonePrefix: "212" },
  { code: "DZ", name: "Algeria", phonePrefix: "213" },
  { code: "TN", name: "Tunisia", phonePrefix: "216" },
  { code: "LY", name: "Libya", phonePrefix: "218" },
  { code: "GM", name: "Gambia", phonePrefix: "220" },
  { code: "SN", name: "Senegal", phonePrefix: "221" },
  { code: "MR", name: "Mauritania", phonePrefix: "222" },
  { code: "ML", name: "Mali", phonePrefix: "223" },
  { code: "GN", name: "Guinea", phonePrefix: "224" },
  { code: "CI", name: "Ivory Coast", phonePrefix: "225" },
  { code: "BF", name: "Burkina Faso", phonePrefix: "226" },
  { code: "NE", name: "Niger", phonePrefix: "227" },
  { code: "TG", name: "Togo", phonePrefix: "228" },
  { code: "BJ", name: "Benin", phonePrefix: "229" },
  { code: "MU", name: "Mauritius", phonePrefix: "230" },
  { code: "LR", name: "Liberia", phonePrefix: "231" },
  { code: "SL", name: "Sierra Leone", phonePrefix: "232" },
  { code: "GH", name: "Ghana", phonePrefix: "233" },
  { code: "NG", name: "Nigeria", phonePrefix: "234" },
  { code: "TD", name: "Chad", phonePrefix: "235" },
  { code: "CF", name: "Centrafrique", phonePrefix: "236" },
  { code: "CM", name: "Cameroon", phonePrefix: "237" },
  { code: "CV", name: "Cape Verde", phonePrefix: "238" },
  { code: "ST", name: "São Tomé & Príncipe", phonePrefix: "239" },
  { code: "GQ", name: "Equatorial Guinea", phonePrefix: "240" },
  { code: "GA", name: "Gabon", phonePrefix: "241" },
  { code: "CG", name: "Congo", phonePrefix: "242" },
  { code: "CD", name: "DR Congo", phonePrefix: "243" },
  { code: "AO", name: "Angola", phonePrefix: "244" },
  { code: "GW", name: "Guinea-Bissau", phonePrefix: "245" },
  { code: "IO", name: "British Indian Ocean Territory", phonePrefix: "246" },
  { code: "SC", name: "Seychelles", phonePrefix: "248" },
  { code: "SD", name: "Sudan", phonePrefix: "249" },
  { code: "RW", name: "Rwanda", phonePrefix: "250" },
  { code: "ET", name: "Ethiopia", phonePrefix: "251" },
  { code: "SO", name: "Somalia", phonePrefix: "252" },
  { code: "DJ", name: "Djibouti", phonePrefix: "253" },
  { code: "KE", name: "Kenya", phonePrefix: "254" },
  { code: "TZ", name: "Tanzania", phonePrefix: "255" },
  { code: "UG", name: "Uganda", phonePrefix: "256" },
  { code: "BI", name: "Burundi", phonePrefix: "257" },
  { code: "MZ", name: "Mozambique", phonePrefix: "258" },
  { code: "ZM", name: "Zambia", phonePrefix: "260" },
  { code: "MG", name: "Madagascar", phonePrefix: "261" },
  { code: "RE", name: "Réunion", phonePrefix: "262" },
  { code: "ZW", name: "Zimbabwe", phonePrefix: "263" },
  { code: "NA", name: "Namibia", phonePrefix: "264" },
  { code: "MW", name: "Malawi", phonePrefix: "265" },
  { code: "LS", name: "Lesotho", phonePrefix: "266" },
  { code: "BW", name: "Botswana", phonePrefix: "267" },
  { code: "SZ", name: "Eswatini", phonePrefix: "268" },
  { code: "KM", name: "Comoros", phonePrefix: "269" },
  { code: "ER", name: "Eritrea", phonePrefix: "291" },
  { code: "AW", name: "Aruba", phonePrefix: "297" },
  { code: "FO", name: "Faroe Islands", phonePrefix: "298" },
  { code: "GL", name: "Greenland", phonePrefix: "299" },
  { code: "GI", name: "Gibraltar", phonePrefix: "350" },
  { code: "PT", name: "Portugal", phonePrefix: "351" },
  { code: "LU", name: "Luxembourg", phonePrefix: "352" },
  { code: "IE", name: "Ireland", phonePrefix: "353" },
  { code: "IS", name: "Iceland", phonePrefix: "354" },
  { code: "AL", name: "Albania", phonePrefix: "355" },
  { code: "MT", name: "Malta", phonePrefix: "356" },
  { code: "CY", name: "Cyprus", phonePrefix: "357" },
  { code: "FI", name: "Finland", phonePrefix: "358" },
  { code: "BG", name: "Bulgaria", phonePrefix: "359" },
  { code: "LT", name: "Lithuania", phonePrefix: "370" },
  { code: "LV", name: "Latvia", phonePrefix: "371" },
  { code: "EE", name: "Estonia", phonePrefix: "372" },
  { code: "MD", name: "Moldova", phonePrefix: "373" },
  { code: "AM", name: "Armenia", phonePrefix: "374" },
  { code: "BY", name: "Belarus", phonePrefix: "375" },
  { code: "AD", name: "Andorra", phonePrefix: "376" },
  { code: "MC", name: "Monaco", phonePrefix: "377" },
  { code: "SM", name: "San Marino", phonePrefix: "378" },
  { code: "UA", name: "Ukraine", phonePrefix: "380" },
  { code: "RS", name: "Serbia", phonePrefix: "381" },
  { code: "ME", name: "Montenegro", phonePrefix: "382" },
  { code: "XK", name: "Kosovo", phonePrefix: "383" },
  { code: "HR", name: "Croatia", phonePrefix: "385" },
  { code: "SI", name: "Slovenia", phonePrefix: "386" },
  { code: "BA", name: "Bosnia & Herzegovina", phonePrefix: "387" },
  { code: "MK", name: "North Macedonia", phonePrefix: "389" },
  { code: "CZ", name: "Czech Republic", phonePrefix: "420" },
  { code: "SK", name: "Slovakia", phonePrefix: "421" },
  { code: "LI", name: "Liechtenstein", phonePrefix: "423" },
  { code: "FK", name: "Falkland Islands", phonePrefix: "500" },
  { code: "BZ", name: "Belize", phonePrefix: "501" },
  { code: "GT", name: "Guatemala", phonePrefix: "502" },
  { code: "SV", name: "El Salvador", phonePrefix: "503" },
  { code: "HN", name: "Honduras", phonePrefix: "504" },
  { code: "NI", name: "Nicaragua", phonePrefix: "505" },
  { code: "CR", name: "Costa Rica", phonePrefix: "506" },
  { code: "PA", name: "Panama", phonePrefix: "507" },
  { code: "PM", name: "Saint Pierre & Miquelon", phonePrefix: "508" },
  { code: "HT", name: "Haiti", phonePrefix: "509" },
  { code: "GP", name: "Guadeloupe", phonePrefix: "590" },
  { code: "BO", name: "Bolivia", phonePrefix: "591" },
  { code: "GY", name: "Guyana", phonePrefix: "592" },
  { code: "EC", name: "Ecuador", phonePrefix: "593" },
  { code: "PY", name: "Paraguay", phonePrefix: "595" },
  { code: "MQ", name: "Martinique", phonePrefix: "596" },
  { code: "SR", name: "Suriname", phonePrefix: "597" },
  { code: "UY", name: "Uruguay", phonePrefix: "598" },
  { code: "AN", name: "Netherlands Antilles", phonePrefix: "599" },
  { code: "TL", name: "Timor-Leste", phonePrefix: "670" },
  { code: "NF", name: "Norfolk Island", phonePrefix: "672" },
  { code: "BN", name: "Brunei", phonePrefix: "673" },
  { code: "NR", name: "Nauru", phonePrefix: "674" },
  { code: "PG", name: "Papua New Guinea", phonePrefix: "675" },
  { code: "TO", name: "Tonga", phonePrefix: "676" },
  { code: "SB", name: "Solomon Islands", phonePrefix: "677" },
  { code: "VU", name: "Vanuatu", phonePrefix: "678" },
  { code: "FJ", name: "Fiji", phonePrefix: "679" },
  { code: "PW", name: "Palau", phonePrefix: "680" },
  { code: "WF", name: "Wallis & Futuna", phonePrefix: "681" },
  { code: "CK", name: "Cook Islands", phonePrefix: "682" },
  { code: "NU", name: "Niue", phonePrefix: "683" },
  { code: "WS", name: "Samoa", phonePrefix: "685" },
  { code: "KI", name: "Kiribati", phonePrefix: "686" },
  { code: "NC", name: "New Caledonia", phonePrefix: "687" },
  { code: "TV", name: "Tuvalu", phonePrefix: "688" },
  { code: "PF", name: "French Polynesia", phonePrefix: "689" },
  { code: "TK", name: "Tokelau", phonePrefix: "690" },
  { code: "FM", name: "Micronesia", phonePrefix: "691" },
  { code: "MH", name: "Marshall Islands", phonePrefix: "692" },
  { code: "KP", name: "North Korea", phonePrefix: "850" },
  { code: "HK", name: "Hong Kong", phonePrefix: "852" },
  { code: "MO", name: "Macau", phonePrefix: "853" },
  { code: "KH", name: "Cambodia", phonePrefix: "855" },
  { code: "LA", name: "Laos", phonePrefix: "856" },
  { code: "BD", name: "Bangladesh", phonePrefix: "880" },
  { code: "TW", name: "Taiwan", phonePrefix: "886" },
  { code: "MV", name: "Maldives", phonePrefix: "960" },
  { code: "LB", name: "Lebanon", phonePrefix: "961" },
  { code: "JO", name: "Jordan", phonePrefix: "962" },
  { code: "SY", name: "Syria", phonePrefix: "963" },
  { code: "IQ", name: "Iraq", phonePrefix: "964" },
  { code: "KW", name: "Kuwait", phonePrefix: "965" },
  { code: "SA", name: "Saudi Arabia", phonePrefix: "966" },
  { code: "YE", name: "Yemen", phonePrefix: "967" },
  { code: "OM", name: "Oman", phonePrefix: "968" },
  { code: "PS", name: "Palestine", phonePrefix: "970" },
  { code: "AE", name: "United Arab Emirates", phonePrefix: "971" },
  { code: "IL", name: "Israel", phonePrefix: "972" },
  { code: "BH", name: "Bahrain", phonePrefix: "973" },
  { code: "QA", name: "Qatar", phonePrefix: "974" },
  { code: "BT", name: "Bhutan", phonePrefix: "975" },
  { code: "MN", name: "Mongolia", phonePrefix: "976" },
  { code: "NP", name: "Nepal", phonePrefix: "977" },
  { code: "TJ", name: "Tajikistan", phonePrefix: "992" },
  { code: "TM", name: "Turkmenistan", phonePrefix: "993" },
  { code: "AZ", name: "Azerbaijan", phonePrefix: "994" },
  { code: "GE", name: "Georgia", phonePrefix: "995" },
  { code: "KG", name: "Kyrgyzstan", phonePrefix: "996" },
  { code: "UZ", name: "Uzbekistan", phonePrefix: "998" },
];

export function getFlagEmoji(countryCode: string): string {
  if (!countryCode || countryCode.length !== 2) return "🌍";
  try {
    return countryCode
      .toUpperCase()
      .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
  } catch {
    return "🌍";
  }
}
