// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/manual-deposit/Current.tsx": () => import("../components/mockups/manual-deposit/Current.tsx"),
  "./components/mockups/manual-deposit/XPingManualDeposit.tsx": () => import("../components/mockups/manual-deposit/XPingManualDeposit.tsx")
};
